ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'VEHICLE_ASSIGNED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TRIP_ASSIGNED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ACCOUNT_UPDATED';

ALTER TABLE "users"
ADD COLUMN IF NOT EXISTS "language" TEXT NOT NULL DEFAULT 'ar';